Wrapper script: improve portability & simplify interface.
(see inline comments for more info on why these changes were made)

diff --git a/bin/ultratrace b/bin/ultratrace
--- a/bin/ultratrace
+++ b/bin/ultratrace
@@ -5,14 +5,20 @@
 # This _should_ support both MacOS and Linux, but not
 # Windows.
 
-if [ $# -eq 1 ] ; then
-  P=$(readlink -f "$1")
-fi
+# Exit early if any of our commands fail.
+set -euo pipefail
 
-cd "$(dirname "$(readlink "$0")")" || exit
-[[ "$(basename "$(pwd)")" == bin ]] && cd ..
-if [ $# -eq 1 ] ; then
-  python3 -m ultratrace "$P"
-else
-  python3 -m ultratrace "$@"
-fi
+__realpath() {
+    # It looks like getting readlink(1) and/or realpath(1) to work in
+    # a reliable cross-platform way is probably difficult ... so let's
+    # just let Python do it for us :^)
+    python3 -c "import os; print(os.path.realpath('$1'))"
+}
+
+# `cd` to the repository root.
+cd "$(basename "$(__realpath "$0")")/.."
+
+# Pass all arguments through to `ultratrace`.  We should be letting the
+# argparse section of `__main__.py` be handling errors and generating nice
+# user-facing text.
+python3 -m ultratrace "$@"
